### PR TITLE
multiSelectCombobox - Default Selected Values 

### PR DESCRIPTION
**Pull request by jcallahan526**
First off thanks for creating the multiSelectCombobox - it is really sweet!
I needed the ability to have default selected values.  I added an @api method to the the multiSelectCombobox.js which I am calling from my parent.

### CODE REVIEW

**Comment by svierk** [comment]
Hi @jcallahan526, 
thank you very much for the positive feedback. I'm glad that you like the component and I am also happy when people contribute enhancements or even new components. 

In this case, however, what you want to achieve is already possible in a simpler way with the existing component. If I understand correctly, you would like to have certain values preselected when loading the component. To do this, you only need to pass them with “selected = true” in the combobox options, as follows:

```
options = [
  {
    label: "Option 1",
    value: "option1",
    selected: true
  },
  {
    label: "Option 2",
    value: "option2"
  },
]
```

I have also just slightly adapted the JSDoc comments in the LWC to make this clearer.

**Comment by jcallahan526** [comment]
thanks!  The only downside of this it is does not set the SelectedItems

image

**Comment by svierk** [comment]
I just tested the component again yesterday and unfortunately I have to admit that I can't reproduce it, it works perfectly for me at least. Here is what I did:

1. I define my combobox options in a parent LWC like:
image

2. In the HTML template of the parent component I include the combobox LWC like:
image

3. This is what I get on load:
image

In case the behavior is somehow different for you, please provide a few more details.

**Comment by jcallahan526** [comment]
Thanks for your help!  I see what is going on....
You are using a constant for the options and I am using a handler so initially my options are null.  In my pull request I have included the "workingTest" lwc.  When I set the options using a constant the selected values are displayed, however with the handler they are not.   
In the multiSelectCombobox.js I added a setter for a new option "selectedValues".  This will run the streamlined handleSelectedValues to update the options  and currentOptions then run the setSelection

**Comment by svierk** [comment]
In your example try annotating monthYearOptions with @track. That should make the variable responsive to changes and also pass them correctly to the child component to recognize this change.

Please also let me know if I can close the pull request or if you are considering contributing a change to the component.

**Comment by jcallahan526** [comment]
adding @track did not work for me

**Comment by svierk** [comment]
Since the PR still contains temporary tests and other none-mergeable component changes, I will close the PR for now. Please feel free to reopen it or create a new one if it contains cleaned up, mergeable contributions.

**Pull request closed without merging**
